name: paper-judge
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pytorch
  - torchtext
  - click
  - autopep8
  - typing
  - pip
  - pip: 
    - sentence-transformers
    - wandb
    - pytorch-lightning


